# TOML file for fpm as described at https://fpm.fortran-lang.org/en/spec/manifest.html
name = "M_matrix"
version = "0.1.0"
license = "Public Domain"
author = "John S. Urban"
maintainer = "urbanjost@comcast.net"
copyright = "2020 John S. Urban"
description = " matlab-like interface via procedure calls(LICENSE:PD)"
categories = ["expression parsing"]
keywords = ["fortran", "expression parsing", "matlab"]
homepage = "https://github.com/urbanjost/M_matrix.git"

[build]
   auto-executables = true
   auto-tests = true
   auto-examples = true
   # new default with v0.8.0
   # force module naming rules to avoid collisions with other packages
   #module-naming = true
   # traditional where user can use any module name
   module-naming = false
[install]
   library = true
# new section with v0.8.0
[fortran]
   #implicit-typing = false
   #implicit-external = false
   #source-form = "free"
   # traditional pre-version8 compatibility
   implicit-typing = true
   implicit-external = true
   source-form = "default"

#[[test]]
#name="test_suite"
#source-dir="test"
#main="test_suite_M_matrix.f90"
#[test.dependencies]
#M_framework          = { git = "https://github.com/urbanjost/M_framework.git" }

#[[executable]]
#name="mat"
#source-dir="app"
#main="mat.f90"

[dependencies]
M_framework    = { git = "https://github.com/urbanjost/M_framework.git" }
M_msg          = { git = "https://github.com/urbanjost/M_msg.git" }
M_strings      = { git = "https://github.com/urbanjost/M_strings.git" }
M_history      = { git = "https://github.com/urbanjost/M_history.git" }
M_CLI2         = { git = "https://github.com/urbanjost/M_CLI2.git" }
M_list         = { git = "https://github.com/urbanjost/M_list.git" }
M_io           = { git = "https://github.com/urbanjost/M_io.git" }
M_LA           = { git = "https://github.com/urbanjost/M_LA.git" }
M_intrinsics   = { git = "https://github.com/urbanjost/M_intrinsics.git" }
#
#To specify a build script to be used, put it in the library section of your fpm.toml file, like:
[library]
source-dir="src"
build-script="my_build_script"

#fpm will set the following environment variables to specify some parameters to the build script:
#
#    FC – The Fortran compiler to be used.
#    FFLAGS – The flags that should be passed to the Fortran compiler.
#    BUILD_DIR – Where the compiled files should be placed.
#    INCLUDE_DIRS – The folders where any dependencies can be found,
#    space separated. It is then the responsibility of the build script
#    to generate the appropriate include flags.

# Additionally, script will be called with the name of the archive (*.a
# file) that should be produced as the command line argument.
