M_strings: /home/urbanjs/venus/V600/github/M_matrix/src/source/FODDER/mmm.f90 File Reference
mmm.f90 File Reference
Modules
module m_matrix
Functions/Subroutines
subroutine, public m_matrix::mat88 (init, string0)
subroutine m_matrix::mat_err (n)
subroutine m_matrix::mat_files (lunit, iname)
subroutine m_matrix::mat_getsym ()
subroutine m_matrix::mat_str2buf (string, buf, lrecl)
subroutine m_matrix::mat_buf2str (string, buf, lrecl)
subroutine m_matrix::mat_hilber (a, lda, n)
subroutine m_matrix::mat_matfn6 ()
subroutine m_matrix::mat_funs (id)
subroutine m_matrix::mat_putid (x, y)
subroutine m_matrix::mat_getval (s)
subroutine m_matrix::mat_getch ()
doubleprecision function m_matrix::mat_wdotur (n, xr, xi, incx, yr, yi, incy)
subroutine m_matrix::mat_appnum (rval, string, ilen, ierr)
subroutine m_matrix::mat_wcopy (n, xr, xi, incx, yr, yi, incy)
subroutine m_matrix::mat_wdiv (ar, ai, br, bi, cr, ci)
subroutine m_matrix::mat_wset (n, xr, xi, yr, yi, incy)
subroutine m_matrix::mat_base (x, b, eps, s, n)
subroutine m_matrix::mat_wswap (n, xr, xi, incx, yr, yi, incy)
doubleprecision function m_matrix::mat_pythag (a, b)
subroutine m_matrix::mat_print (ID, K)
subroutine m_matrix::mat_wsqrt (xr, xi, yr, yi)
subroutine m_matrix::mat_wlog (xr, xi, yr, yi)
subroutine m_matrix::ml_formz (lunit, x, y)
subroutine m_matrix::mat_rref (ar, ai, lda, m, n, eps)
integer function m_matrix::mat_iwamax (n, xr, xi, incx)
doubleprecision function m_matrix::mat_flop (x)
logical function m_matrix::mat_eqid (x, y)
doubleprecision function m_matrix::mat_round (x)
subroutine m_matrix::mat_make_help (io)
subroutine m_matrix::mat_make_manual (io)
subroutine matx_waxpy (n, sr, si, xr, xi, incx, yr, yi, incy)
subroutine mat_parse (INIT)
subroutine ml_clause ()
subroutine ml_comand (id)
subroutine ml_expr ()
subroutine ml_factor ()
subroutine ml_getlin ()
subroutine ml_xchar (BUF, K)
subroutine ml_plot (LPLOT, X, Y, N, P, K)
subroutine ml_prntid (ID, ARGCNT)
subroutine ml_prompt (PAUSE)
subroutine ml_matfn1 ()
subroutine ml_matfn2 ()
subroutine ml_matfn3 ()
subroutine ml_matfn4 ()
subroutine ml_matfn5 ()
subroutine ml_rat (x, len, maxd, a, b, d)
subroutine ml_savlod (LSAVE, ID, M, N, IMG, JOB, XREAL, XIMAG)
subroutine ml_stack1 (OP)
subroutine ml_stack2 (OP)
subroutine ml_stackg (ID)
subroutine ml_stackp (ID)
subroutine ml_term ()
subroutine ml_wgeco (AR, AI, LDA, N, IPVT, RCOND, ZR, ZI)
subroutine ml_wgefa (AR, AI, LDA, N, IPVT, INFO)
subroutine ml_wgesl (AR, AI, LDA, N, IPVT, BR, BI, JOB)
subroutine ml_wgedi (AR, AI, LDA, N, IPVT, DETR, DETI, WORKR, WORKI, JOB)
subroutine ml_wpofa (AR, AI, LDA, N, INFO)
subroutine ml_htridi (NM, N, AR, AI, D, E, E2, TAU)
subroutine ml_htribk (NM, N, AR, AI, TAU, M, ZR, ZI)
subroutine ml_imtql2 (NM, N, D, E, Z, IERR, JOB)
subroutine ml_corth (NM, N, LOW, IGH, AR, AI, ORTR, ORTI)
subroutine ml_comqr3 (nm, n, low, igh, ortr, orti, hr, hi, wr, wi, zr, zi, ierr, job)
subroutine ml_wsvdc (XR, XI, LDX, N, P, SR, SI, ER, EI, UR, UI, LDU, VR, VI, LDV, WORKR, WORKI, JOB, INFO)
subroutine ml_wqrdc (XR, XI, LDX, N, P, QRAUXR, QRAUXI, JPVT, WORKR, WORKI, JOB)
subroutine ml_wqrsl (XR, XI, LDX, N, K, QRAUXR, QRAUXI, YR, YI, QYR, QYI, QTYR, QTYI, BR, BI, RSDR, RSDI, XBR, XBI, JOB, INFO)
subroutine ml_magic (a, lda, n)
subroutine ml_wmul (ar, ai, br, bi, cr, ci)
subroutine ml_wsign (xr, xi, yr, yi, zr, zi)
subroutine ml_watan (xr, xi, yr, yi)
subroutine ml_rset (n, dx, dy, incy)
subroutine ml_rswap (n, x, incx, y, incy)
subroutine ml_rrot (N, DX, INCX, DY, INCY, C, S)
subroutine ml_rrotg (DA, DB, C, S)
subroutine ml_wrscal (N, S, XR, XI, INCX)
subroutine ml_wscal (N, SR, SI, XR, XI, INCX)
doubleprecision function ml_urand (IY)
doubleprecision function ml_wnrm2 (N, XR, XI, INCX)
doubleprecision function ml_wasum (N, XR, XI, INCX)
doubleprecision function ml_wdotui (N, XR, XI, INCX, YR, YI, INCY)
doubleprecision function ml_wdotcr (N, XR, XI, INCX, YR, YI, INCY)
doubleprecision function ml_wdotci (N, XR, XI, INCX, YR, YI, INCY)
subroutine ml_2chars (DINTS, M, ICOUNT, IROW, STRING)
program bigmat
Variables
integer, parameter m_matrix::bigmem =200005
character(len=1024), save m_matrix::stringq
integer, save m_matrix::istringq
integer, save m_matrix::initq
integer, parameter m_matrix::ialf =78
doubleprecision, dimension(bigmem) m_matrix::stkr
doubleprecision, dimension(bigmem) m_matrix::stki
integer, dimension(4, 48) m_matrix::idstk
integer, dimension(48) m_matrix::lstk
integer, dimension(48) m_matrix::mstk
integer, dimension(48) m_matrix::nstk
integer m_matrix::vsize
integer m_matrix::lsize
integer m_matrix::bot
integer m_matrix::top
integer, dimension(ialf) m_matrix::alfa
integer, dimension(ialf) m_matrix::alfb
integer m_matrix::alflq
integer m_matrix::case
integer, dimension(4, 32) m_matrix::ids
integer, dimension(32) m_matrix::pstk
integer, dimension(32) m_matrix::rstk
integer m_matrix::psize
integer m_matrix::pt
integer m_matrix::ptz
integer m_matrix::ddt
integer m_matrix::err
integer m_matrix::fmt
integer, dimension(4) m_matrix::lct
integer, dimension(1024) m_matrix::lin
integer, dimension(6) m_matrix::lpt
integer m_matrix::hio
integer m_matrix::rio
integer m_matrix::rte
integer m_matrix::wte
integer m_matrix::fe
integer m_matrix::sym
integer, dimension(4) m_matrix::syn
integer, dimension(1024) m_matrix::buf
integer m_matrix::chra
integer, dimension(2) m_matrix::flp
integer m_matrix::fin
integer m_matrix::fun
integer m_matrix::lhs
integer m_matrix::rhs
integer, dimension(2) m_matrix::ran
character(len=ialf), parameter m_matrix::ch_a ='0123456789abcdefghijklmnopqrstuvwxyz ();:+-*/\=.,''<>ABCDEFGHIJKLMNOPQRSTUVWXYZ'
character(len=ialf), parameter m_matrix::ch_b ='0123456789abcdefghijklmnopqrstuvwxyz {};|+-*/$=@,"[]ABCDEFGHIJKLMNOPQRSTUVWXYZ'
integer, parameter m_matrix::eol =99
Function/Subroutine Documentation
bigmat()
program bigmat
References m_matrix::mat88().
mat_parse()
subroutine mat_parse (INIT)
References m_matrix::mat_eqid(), ml_clause(), ml_comand(), ml_expr(), ml_factor(), ml_getlin(), ml_prompt(), ml_stackp(), and ml_term().
matx_waxpy()
subroutine matx_waxpy (integer n, doubleprecision sr, doubleprecision si, doubleprecision, dimension(*) xr, doubleprecision, dimension(*) xi, integer incx, doubleprecision, dimension(*) yr, doubleprecision, dimension(*) yi, integer incy)
References m_matrix::mat_flop().
ml_2chars()
subroutine ml_2chars (doubleprecision, dimension(m,icount) DINTS, M, integer ICOUNT, IROW, character, dimension(*) STRING)
References m_matrix::ch_a.
ml_clause()
subroutine ml_clause
References m_matrix::mat_eqid(), and ml_stackp().
ml_comand()
subroutine ml_comand (integer, dimension(4) id)
References m_matrix::mat_eqid(), ml_getlin(), ml_prntid(), and ml_stackp().
ml_comqr3()
subroutine ml_comqr3 (integer nm, integer n, integer low, integer igh, doubleprecision, dimension(igh) ortr, doubleprecision, dimension(igh) orti, doubleprecision, dimension(nm,n) hr, doubleprecision, dimension(nm,n) hi, doubleprecision, dimension(n) wr, doubleprecision, dimension(n) wi, doubleprecision, dimension(nm,n) zr, doubleprecision, dimension(nm,n) zi, integer ierr, job)
References m_matrix::mat_flop(), m_matrix::mat_pythag(), m_matrix::mat_wdiv(), and m_matrix::mat_wsqrt().
ml_corth()
subroutine ml_corth (integer NM, integer N, integer LOW, integer IGH, doubleprecision, dimension(nm,n) AR, doubleprecision, dimension(nm,n) AI, doubleprecision, dimension(igh) ORTR, doubleprecision, dimension(igh) ORTI)
References m_matrix::mat_flop(), and m_matrix::mat_pythag().
ml_expr()
subroutine ml_expr
References m_matrix::ddt, m_matrix::err, m_matrix::lin, m_matrix::lpt, m_matrix::mat_err(), m_matrix::mat_getsym(), m_matrix::mat_putid(), ml_stack1(), ml_stack2(), m_matrix::psize, m_matrix::pstk, m_matrix::pt, m_matrix::rhs, m_matrix::rstk, m_matrix::sym, and m_matrix::syn.
ml_factor()
subroutine ml_factor
References m_matrix::bot, m_matrix::chra, m_matrix::ddt, m_matrix::eol, m_matrix::err, m_matrix::fin, m_matrix::fun, m_matrix::ialf, m_matrix::ids, m_matrix::lct, m_matrix::lin, m_matrix::lpt, m_matrix::lstk, m_matrix::mat_err(), m_matrix::mat_funs(), m_matrix::mat_getch(), m_matrix::mat_getsym(), m_matrix::mat_putid(), ml_getlin(), ml_stack1(), ml_stack2(), ml_stackg(), m_matrix::mstk, m_matrix::nstk, m_matrix::pstk, m_matrix::pt, m_matrix::rhs, m_matrix::rstk, m_matrix::stki, m_matrix::stkr, m_matrix::sym, m_matrix::syn, m_matrix::top, and m_matrix::vsize.
ml_getlin()
subroutine ml_getlin
References m_matrix::alfa, m_matrix::buf, m_matrix::initq, m_matrix::istringq, m_matrix::lpt, m_matrix::mat_str2buf(), m_matrix::rio, and m_matrix::stringq.
ml_htribk()
subroutine ml_htribk (integer NM, integer N, doubleprecision, dimension(nm,n) AR, doubleprecision, dimension(nm,n) AI, doubleprecision, dimension(2,n) TAU, integer M, doubleprecision, dimension(nm,m) ZR, doubleprecision, dimension(nm,m) ZI)
References m_matrix::mat_flop().
ml_htridi()
subroutine ml_htridi (integer NM, integer N, doubleprecision, dimension(nm,n) AR, doubleprecision, dimension(nm,n) AI, doubleprecision, dimension(n) D, doubleprecision, dimension(n) E, doubleprecision, dimension(n) E2, doubleprecision, dimension(2,n) TAU)
References m_matrix::mat_flop(), and m_matrix::mat_pythag().
ml_imtql2()
subroutine ml_imtql2 (integer NM, integer N, doubleprecision, dimension(n) D, doubleprecision, dimension(n) E, doubleprecision, dimension(nm,n) Z, integer IERR, JOB)
References m_matrix::mat_flop().
ml_magic()
subroutine ml_magic (doubleprecision, dimension(lda,n) a, lda, n)
References ml_rswap().
ml_matfn1()
subroutine ml_matfn1
References m_matrix::mat_flop(), ml_rset(), ml_wgeco(), ml_wgedi(), ml_wgefa(), ml_wgesl(), ml_wpofa(), and ml_wscal().
ml_matfn2()
subroutine ml_matfn2
References m_matrix::bot, m_matrix::ddt, m_matrix::err, m_matrix::fin, m_matrix::fun, m_matrix::lhs, m_matrix::lstk, m_matrix::mat_err(), m_matrix::mat_flop(), m_matrix::mat_pythag(), m_matrix::mat_round(), m_matrix::mat_wcopy(), m_matrix::mat_wdiv(), m_matrix::mat_wlog(), m_matrix::mat_wset(), m_matrix::mat_wsqrt(), matx_waxpy(), ml_comqr3(), ml_corth(), ml_htribk(), ml_htridi(), ml_imtql2(), ml_watan(), ml_wmul(), ml_wscal(), m_matrix::mstk, m_matrix::nstk, m_matrix::stki, m_matrix::stkr, and m_matrix::top.
ml_matfn3()
subroutine ml_matfn3
References m_matrix::mat_flop(), m_matrix::mat_iwamax(), ml_wrscal(), and ml_wsvdc().
ml_matfn4()
subroutine ml_matfn4
References m_matrix::mat_flop(), ml_stack1(), ml_wqrdc(), and ml_wqrsl().
ml_matfn5()
subroutine ml_matfn5
References m_matrix::mat_flop(), ml_plot(), ml_rat(), ml_rset(), ml_savlod(), ml_stack1(), and ml_stackp().
ml_plot()
subroutine ml_plot (LPLOT, doubleprecision, dimension(n) X, doubleprecision, dimension(n) Y, N, doubleprecision, dimension(*) P, K)
ml_prntid()
subroutine ml_prntid (integer, dimension(4,*) ID, integer ARGCNT)
References m_matrix::alfa, m_matrix::mat_buf2str(), and m_matrix::wte.
ml_prompt()
subroutine ml_prompt (integer PAUSE)
References m_matrix::rte, and m_matrix::wte.
ml_rat()
subroutine ml_rat (doubleprecision x, integer len, integer maxd, doubleprecision a, doubleprecision b, doubleprecision, dimension(len) d)
References m_matrix::ddt, m_matrix::mat_round(), and m_matrix::wte.
ml_rrot()
subroutine ml_rrot (integer N, doubleprecision, dimension(*) DX, integer INCX, doubleprecision, dimension(*) DY, integer INCY, doubleprecision C, doubleprecision S)
References m_matrix::mat_flop().
ml_rrotg()
subroutine ml_rrotg (doubleprecision DA, doubleprecision DB, doubleprecision C, doubleprecision S)
References m_matrix::mat_flop(), and m_matrix::mat_pythag().
ml_rset()
subroutine ml_rset (n, doubleprecision dx, doubleprecision, dimension(*) dy, incy)
ml_rswap()
subroutine ml_rswap (n, doubleprecision, dimension(*) x, incx, doubleprecision, dimension(*) y, incy)
ml_savlod()
subroutine ml_savlod (integer LSAVE, integer, dimension(4) ID, integer M, integer N, integer IMG, integer JOB, doubleprecision, dimension(*) XREAL, doubleprecision, dimension(*) XIMAG)
References m_matrix::mat_buf2str(), and m_matrix::mat_str2buf().
ml_stack1()
subroutine ml_stack1 (integer OP)
References m_matrix::bot, m_matrix::ddt, m_matrix::err, m_matrix::lstk, m_matrix::mat_err(), m_matrix::mat_wcopy(), ml_wrscal(), m_matrix::mstk, m_matrix::nstk, m_matrix::stki, m_matrix::stkr, and m_matrix::top.
ml_stack2()
subroutine ml_stack2 (integer OP)
References m_matrix::mat_flop(), matx_waxpy(), ml_wmul(), ml_wrscal(), and ml_wscal().
ml_stackg()
subroutine ml_stackg (integer, dimension(4) ID)
References m_matrix::mat_eqid().
ml_stackp()
subroutine ml_stackp (integer, dimension(4) ID)
References m_matrix::mat_eqid().
ml_term()
subroutine ml_term
References m_matrix::ddt, m_matrix::err, m_matrix::fun, m_matrix::mat_appnum(), m_matrix::mat_err(), m_matrix::mat_getsym(), ml_stack2(), m_matrix::pstk, m_matrix::pt, m_matrix::rstk, and m_matrix::sym.
ml_urand()
doubleprecision function ml_urand (integer IY)
ml_wasum()
doubleprecision function ml_wasum (N, doubleprecision, dimension(*) XR, doubleprecision, dimension(*) XI, INCX)
References m_matrix::mat_flop().
ml_watan()
subroutine ml_watan (doubleprecision xr, doubleprecision xi, doubleprecision yr, doubleprecision yi)
References m_matrix::mat_err(), m_matrix::mat_wdiv(), and m_matrix::mat_wlog().
ml_wdotci()
doubleprecision function ml_wdotci (N, doubleprecision, dimension(*) XR, doubleprecision, dimension(*) XI, INCX, doubleprecision, dimension(*) YR, doubleprecision, dimension(*) YI, INCY)
References m_matrix::mat_flop().
ml_wdotcr()
doubleprecision function ml_wdotcr (N, doubleprecision, dimension(*) XR, doubleprecision, dimension(*) XI, INCX, doubleprecision, dimension(*) YR, doubleprecision, dimension(*) YI, INCY)
References m_matrix::mat_flop().
ml_wdotui()
doubleprecision function ml_wdotui (N, doubleprecision, dimension(*) XR, doubleprecision, dimension(*) XI, INCX, doubleprecision, dimension(*) YR, doubleprecision, dimension(*) YI, INCY)
References m_matrix::mat_flop().
ml_wgeco()
subroutine ml_wgeco (doubleprecision, dimension(lda,*) AR, doubleprecision, dimension(lda,*) AI, integer LDA, integer N, integer, dimension(*) IPVT, doubleprecision RCOND, doubleprecision, dimension(*) ZR, doubleprecision, dimension(*) ZI)
References m_matrix::mat_flop(), m_matrix::mat_wdiv(), matx_waxpy(), ml_wgefa(), ml_wmul(), ml_wrscal(), and ml_wsign().
ml_wgedi()
subroutine ml_wgedi (doubleprecision, dimension(lda,*) AR, doubleprecision, dimension(lda,*) AI, integer LDA, integer N, integer, dimension(*) IPVT, doubleprecision, dimension(2) DETR, doubleprecision, dimension(2) DETI, doubleprecision, dimension(*) WORKR, doubleprecision, dimension(*) WORKI, integer JOB)
References m_matrix::mat_wdiv(), m_matrix::mat_wswap(), matx_waxpy(), ml_wmul(), and ml_wscal().
ml_wgefa()
subroutine ml_wgefa (doubleprecision, dimension(lda,*) AR, doubleprecision, dimension(lda,*) AI, integer LDA, integer N, integer, dimension(*) IPVT, integer INFO)
References m_matrix::mat_iwamax(), m_matrix::mat_wdiv(), matx_waxpy(), and ml_wscal().
ml_wgesl()
subroutine ml_wgesl (doubleprecision, dimension(lda,*) AR, doubleprecision, dimension(lda,*) AI, integer LDA, integer N, integer, dimension(*) IPVT, doubleprecision, dimension(*) BR, doubleprecision, dimension(*) BI, integer JOB)
References m_matrix::mat_wdiv(), and matx_waxpy().
ml_wmul()
subroutine ml_wmul (doubleprecision ar, doubleprecision ai, doubleprecision br, doubleprecision bi, doubleprecision cr, doubleprecision ci)
References m_matrix::mat_flop().
ml_wnrm2()
doubleprecision function ml_wnrm2 (N, doubleprecision, dimension(*) XR, doubleprecision, dimension(*) XI, INCX)
References m_matrix::mat_pythag().
ml_wpofa()
subroutine ml_wpofa (doubleprecision, dimension(lda,*) AR, doubleprecision, dimension(lda,*) AI, LDA, N, INFO)
References m_matrix::mat_wdiv().
ml_wqrdc()
subroutine ml_wqrdc (doubleprecision, dimension(ldx,*) XR, doubleprecision, dimension(ldx,*) XI, integer LDX, integer N, integer P, doubleprecision, dimension(*) QRAUXR, doubleprecision, dimension(*) QRAUXI, integer, dimension(*) JPVT, doubleprecision, dimension(*) WORKR, doubleprecision, dimension(*) WORKI, integer JOB)
References m_matrix::mat_flop(), m_matrix::mat_pythag(), m_matrix::mat_wdiv(), m_matrix::mat_wswap(), matx_waxpy(), ml_wscal(), and ml_wsign().
ml_wqrsl()
subroutine ml_wqrsl (doubleprecision, dimension(ldx,*) XR, doubleprecision, dimension(ldx,*) XI, integer LDX, integer N, integer K, doubleprecision, dimension(*) QRAUXR, doubleprecision, dimension(*) QRAUXI, doubleprecision, dimension(*) YR, doubleprecision, dimension(*) YI, doubleprecision, dimension(*) QYR, doubleprecision, dimension(*) QYI, doubleprecision, dimension(*) QTYR, doubleprecision, dimension(*) QTYI, doubleprecision, dimension(*) BR, doubleprecision, dimension(*) BI, doubleprecision, dimension(*) RSDR, doubleprecision, dimension(*) RSDI, doubleprecision, dimension(*) XBR, doubleprecision, dimension(*) XBI, integer JOB, integer INFO)
References m_matrix::mat_wcopy(), m_matrix::mat_wdiv(), and matx_waxpy().
ml_wrscal()
subroutine ml_wrscal (N, doubleprecision S, doubleprecision, dimension(*) XR, doubleprecision, dimension(*) XI, INCX)
References m_matrix::mat_flop().
ml_wscal()
subroutine ml_wscal (N, doubleprecision SR, doubleprecision SI, doubleprecision, dimension(*) XR, doubleprecision, dimension(*) XI, INCX)
References ml_wmul().
ml_wsign()
subroutine ml_wsign (doubleprecision xr, doubleprecision xi, doubleprecision yr, doubleprecision yi, doubleprecision zr, doubleprecision zi)
References m_matrix::mat_pythag(), and ml_wmul().
ml_wsvdc()
subroutine ml_wsvdc (doubleprecision, dimension(ldx,*) XR, doubleprecision, dimension(ldx,*) XI, integer LDX, integer N, integer P, doubleprecision, dimension(*) SR, doubleprecision, dimension(*) SI, doubleprecision, dimension(*) ER, doubleprecision, dimension(*) EI, doubleprecision, dimension(ldu,*) UR, doubleprecision, dimension(ldu,*) UI, integer LDU, doubleprecision, dimension(ldv,*) VR, doubleprecision, dimension(ldv,*) VI, integer LDV, doubleprecision, dimension(*) WORKR, doubleprecision, dimension(*) WORKI, integer JOB, integer INFO)
References m_matrix::mat_flop(), m_matrix::mat_pythag(), m_matrix::mat_wdiv(), m_matrix::mat_wswap(), matx_waxpy(), ml_rrot(), ml_rrotg(), ml_wmul(), ml_wrscal(), ml_wscal(), and ml_wsign().
ml_xchar()
subroutine ml_xchar (integer, dimension(*) BUF, integer K)