M_strings: /home/urbanjs/venus/V600/github/M_matrix/src/source/FODDER/mold.f90 File Reference
mold.f90 File Reference
Functions/Subroutines
program bigmat
subroutine clause
subroutine comand (ID)
subroutine edit (BUF, N)
subroutine error (N)
subroutine expr
subroutine factor
subroutine files (LUNIT, INAME)
double precision function flop (X)
subroutine formz (LUNIT, X, Y)
subroutine funs (ID)
subroutine getch
subroutine getlin
subroutine getsym
subroutine getval (S)
subroutine matfn1
subroutine matfn2
subroutine matfn3
subroutine matfn4
subroutine matfn5
subroutine matfn6
subroutine matlab (INIT)
subroutine parse
subroutine plot (LUNIT, X, Y, N, P, K)
subroutine print (ID, K)
subroutine prntid (ID, ARGCNT)
subroutine prompt (PAUSE)
double precision function pythag (A, B)
subroutine rat (X, LEN, MAXD, A, B, D)
subroutine savlod (LUNIT, ID, M, N, IMG, JOB, XREAL, XIMAG)
subroutine stack1 (OP)
subroutine stack2 (OP)
subroutine stackg (ID)
subroutine stackp (ID)
subroutine term
subroutine user (A, M, N, S, T)
subroutine xchar (BUF, K)
subroutine wgeco (AR, AI, LDA, N, IPVT, RCOND, ZR, ZI)
subroutine wgefa (AR, AI, LDA, N, IPVT, INFO)
subroutine wgesl (AR, AI, LDA, N, IPVT, BR, BI, JOB)
subroutine wgedi (AR, AI, LDA, N, IPVT, DETR, DETI, WORKR, WORKI, JOB)
subroutine wpofa (AR, AI, LDA, N, INFO)
subroutine rref (AR, AI, LDA, M, N, EPS)
subroutine hilber (A, LDA, N)
subroutine htridi (NM, N, AR, AI, D, E, E2, TAU)
subroutine htribk (NM, N, AR, AI, TAU, M, ZR, ZI)
subroutine imtql2 (NM, N, D, E, Z, IERR, JOB)
subroutine corth (NM, N, LOW, IGH, AR, AI, ORTR, ORTI)
subroutine comqr3 (NM, N, LOW, IGH, ORTR, ORTI, HR, HI, WR, WI, ZR, ZI, IERR, JOB)
subroutine wsvdc (XR, XI, LDX, N, P, SR, SI, ER, EI, UR, UI, LDU, VR, VI, LDV, WORKR, WORKI, JOB, INFO)
subroutine wqrdc (XR, XI, LDX, N, P, QRAUXR, QRAUXI, JPVT, WORKR, WORKI, JOB)
subroutine wqrsl (XR, XI, LDX, N, K, QRAUXR, QRAUXI, YR, YI, QYR, QYI, QTYR, QTYI, BR, BI, RSDR, RSDI, XBR, XBI, JOB, INFO)
subroutine magic (A, LDA, N)
subroutine base (X, B, EPS, S, N)
double precision function urand (IY)
subroutine wmul (AR, AI, BR, BI, CR, CI)
subroutine wdiv (AR, AI, BR, BI, CR, CI)
subroutine wsign (XR, XI, YR, YI, ZR, ZI)
subroutine wsqrt (XR, XI, YR, YI)
subroutine wlog (XR, XI, YR, YI)
subroutine watan (XR, XI, YR, YI)
double precision function wnrm2 (N, XR, XI, INCX)
double precision function wasum (N, XR, XI, INCX)
integer function iwamax (N, XR, XI, INCX)
subroutine wrscal (N, S, XR, XI, INCX)
subroutine wscal (N, SR, SI, XR, XI, INCX)
subroutine waxpy (N, SR, SI, XR, XI, INCX, YR, YI, INCY)
double precision function wdotur (N, XR, XI, INCX, YR, YI, INCY)
double precision function wdotui (N, XR, XI, INCX, YR, YI, INCY)
double precision function wdotcr (N, XR, XI, INCX, YR, YI, INCY)
double precision function wdotci (N, XR, XI, INCX, YR, YI, INCY)
subroutine wcopy (N, XR, XI, INCX, YR, YI, INCY)
subroutine wset (N, XR, XI, YR, YI, INCY)
subroutine wswap (N, XR, XI, INCX, YR, YI, INCY)
subroutine rset (N, DX, DY, INCY)
subroutine rswap (N, X, INCX, Y, INCY)
subroutine rrot (N, DX, INCX, DY, INCY, C, S)
subroutine rrotg (DA, DB, C, S)
logical function eqid (X, Y)
subroutine putid (X, Y)
double precision function round (X)
double precision function ml_dfloat (I)
Function/Subroutine Documentation
base()
subroutine base (double precision X, double precision B, double precision EPS, double precision, dimension(1) S, N)
bigmat()
program bigmat
References matlab().
clause()
subroutine clause
References error(), getsym(), putid(), stackp(), and wcopy().
comand()
subroutine comand (integer, dimension(4) ID)
References error(), files(), funs(), getsym(), prntid(), and stackp().
comqr3()
subroutine comqr3 (integer NM, integer N, integer LOW, integer IGH, double precision, dimension(igh) ORTR, double precision, dimension(igh) ORTI, double precision, dimension(nm,n) HR, double precision, dimension(nm,n) HI, double precision, dimension(n) WR, double precision, dimension(n) WI, double precision, dimension(nm,n) ZR, double precision, dimension(nm,n) ZI, integer IERR, JOB)
References wdiv(), and wsqrt().
corth()
subroutine corth (integer NM, integer N, integer LOW, integer IGH, double precision, dimension(nm,n) AR, double precision, dimension(nm,n) AI, double precision, dimension(igh) ORTR, double precision, dimension(igh) ORTI)
edit()
subroutine edit (integer, dimension(n) BUF, N)
eqid()
logical function eqid (integer, dimension(4) X, integer, dimension(4) Y)
References y().
error()
subroutine error (integer N)
expr()
subroutine expr
References error(), getsym(), putid(), stack1(), and stack2().
factor()
subroutine factor
References error(), funs(), getch(), getlin(), getsym(), putid(), stack1(), stack2(), and stackg().
files()
subroutine files (integer LUNIT, integer, dimension(256) INAME)
flop()
double precision function flop (double precision X)
formz()
subroutine formz (LUNIT, double precision X, double precision Y)
funs()
subroutine funs (integer, dimension(4) ID)
References prntid().
getch()
subroutine getch
getlin()
subroutine getlin
References edit(), files(), getch(), and putid().
getsym()
subroutine getsym
References getch(), getval(), and prntid().
getval()
subroutine getval (double precision S)
References getch().
hilber()
subroutine hilber (double precision, dimension(lda,n) A, LDA, N)
htribk()
subroutine htribk (integer NM, integer N, double precision, dimension(nm,n) AR, double precision, dimension(nm,n) AI, double precision, dimension(2,n) TAU, integer M, double precision, dimension(nm,m) ZR, double precision, dimension(nm,m) ZI)
htridi()
subroutine htridi (integer NM, integer N, double precision, dimension(nm,n) AR, double precision, dimension(nm,n) AI, double precision, dimension(n) D, double precision, dimension(n) E, double precision, dimension(n) E2, double precision, dimension(2,n) TAU)
imtql2()
subroutine imtql2 (integer NM, integer N, double precision, dimension(n) D, double precision, dimension(n) E, double precision, dimension(nm,n) Z, integer IERR, JOB)
iwamax()
integer function iwamax (N, double precision, dimension(1) XR, double precision, dimension(1) XI, INCX)
References p().
magic()
subroutine magic (double precision, dimension(lda,n) A, LDA, N)
References rswap().
matfn1()
subroutine matfn1
References error(), hilber(), rref(), rset(), wcopy(), wgeco(), wgedi(), wgefa(), wgesl(), wpofa(), wscal(), wset(), and wswap().
matfn2()
subroutine matfn2
References comqr3(), corth(), error(), htribk(), htridi(), imtql2(), watan(), waxpy(), wcopy(), wdiv(), wlog(), wmul(), wscal(), wset(), and wsqrt().
matfn3()
subroutine matfn3
References error(), iwamax(), wcopy(), wrscal(), and wsvdc().
matfn4()
subroutine matfn4
References error(), stack1(), wcopy(), wqrdc(), wqrsl(), wset(), and wswap().
matfn5()
subroutine matfn5
References base(), error(), files(), plot(), print(), putid(), rat(), rset(), savlod(), stack1(), stackp(), and wcopy().
matfn6()
subroutine matfn6
References error(), magic(), rset(), user(), wcopy(), wdiv(), wmul(), and wset().
matlab()
subroutine matlab (INIT)
References files(), matfn1(), matfn2(), matfn3(), matfn4(), matfn5(), matfn6(), parse(), putid(), and wset().
ml_dfloat()
double precision function ml_dfloat (integer I)
parse()
subroutine parse
References clause(), comand(), error(), factor(), files(), funs(), getlin(), getsym(), prompt(), putid(), stackp(), and term().
plot()
subroutine plot (LUNIT, double precision, dimension(n) X, double precision, dimension(n) Y, N, double precision, dimension(1) P, K)
print()
subroutine print (integer, dimension(4) ID, integer K)
References files(), formz(), and prntid().
prntid()
subroutine prntid (integer, dimension(4,1) ID, integer ARGCNT)
prompt()
subroutine prompt (integer PAUSE)
putid()
subroutine putid (integer, dimension(4) X, integer, dimension(4) Y)
pythag()
double precision function pythag (double precision A, double precision B)
References p().
rat()
subroutine rat (double precision X, integer LEN, integer MAXD, double precision A, double precision B, double precision, dimension(len) D)
round()
double precision function round (double precision X)
References y().
rref()
subroutine rref (double precision, dimension(lda,1) AR, double precision, dimension(lda,1) AI, LDA, M, N, double precision EPS)
References iwamax(), waxpy(), wdiv(), wscal(), wset(), and wswap().
rrot()
subroutine rrot (integer N, double precision, dimension(1) DX, integer INCX, double precision, dimension(1) DY, integer INCY, double precision C, double precision S)
rrotg()
subroutine rrotg (double precision DA, double precision DB, double precision C, double precision S)
rset()
subroutine rset (N, double precision DX, double precision, dimension(1) DY, INCY)
rswap()
subroutine rswap (N, double precision, dimension(1) X, INCX, double precision, dimension(1) Y, INCY)
savlod()
subroutine savlod (integer LUNIT, integer, dimension(4) ID, integer M, integer N, integer IMG, integer JOB, double precision, dimension(1) XREAL, double precision, dimension(1) XIMAG)
stack1()
subroutine stack1 (integer OP)
References error(), wcopy(), and wrscal().
stack2()
subroutine stack2 (integer OP)
References error(), waxpy(), wcopy(), wdiv(), wmul(), wrscal(), and wscal().
stackg()
subroutine stackg (integer, dimension(4) ID)
References error(), putid(), and wcopy().
stackp()
subroutine stackp (integer, dimension(4) ID)
References error(), funs(), print(), putid(), wcopy(), and wset().
term()
subroutine term
References error(), getsym(), and stack2().
urand()
double precision function urand (integer IY)
user()
subroutine user (double precision, dimension(m,n) A, M, N, double precision S, double precision T)
wasum()
double precision function wasum (N, double precision, dimension(1) XR, double precision, dimension(1) XI, INCX)
watan()
subroutine watan (double precision XR, double precision XI, double precision YR, double precision YI)
References error(), wdiv(), and wlog().
waxpy()
subroutine waxpy (N, double precision SR, double precision SI, double precision, dimension(1) XR, double precision, dimension(1) XI, INCX, double precision, dimension(1) YR, double precision, dimension(1) YI, INCY)
wcopy()
subroutine wcopy (N, double precision, dimension(1) XR, double precision, dimension(1) XI, INCX, double precision, dimension(1) YR, double precision, dimension(1) YI, INCY)
wdiv()
subroutine wdiv (double precision AR, double precision AI, double precision BR, double precision BI, double precision CR, double precision CI)
References error().
wdotci()
double precision function wdotci (N, double precision, dimension(1) XR, double precision, dimension(1) XI, INCX, double precision, dimension(1) YR, double precision, dimension(1) YI, INCY)
wdotcr()
double precision function wdotcr (N, double precision, dimension(1) XR, double precision, dimension(1) XI, INCX, double precision, dimension(1) YR, double precision, dimension(1) YI, INCY)
wdotui()
double precision function wdotui (N, double precision, dimension(1) XR, double precision, dimension(1) XI, INCX, double precision, dimension(1) YR, double precision, dimension(1) YI, INCY)
wdotur()
double precision function wdotur (N, double precision, dimension(1) XR, double precision, dimension(1) XI, INCX, double precision, dimension(1) YR, double precision, dimension(1) YI, INCY)
wgeco()
subroutine wgeco (double precision, dimension(lda,1) AR, double precision, dimension(lda,1) AI, integer LDA, integer N, integer, dimension(1) IPVT, double precision RCOND, double precision, dimension(1) ZR, double precision, dimension(1) ZI)
References waxpy(), wdiv(), wgefa(), wmul(), wrscal(), and wsign().
wgedi()
subroutine wgedi (double precision, dimension(lda,1) AR, double precision, dimension(lda,1) AI, integer LDA, integer N, integer, dimension(1) IPVT, double precision, dimension(2) DETR, double precision, dimension(2) DETI, double precision, dimension(1) WORKR, double precision, dimension(1) WORKI, integer JOB)
References waxpy(), wdiv(), wmul(), wscal(), and wswap().
wgefa()
subroutine wgefa (double precision, dimension(lda,1) AR, double precision, dimension(lda,1) AI, integer LDA, integer N, integer, dimension(1) IPVT, integer INFO)
References waxpy(), wdiv(), and wscal().
wgesl()
subroutine wgesl (double precision, dimension(lda,1) AR, double precision, dimension(lda,1) AI, integer LDA, integer N, integer, dimension(1) IPVT, double precision, dimension(1) BR, double precision, dimension(1) BI, integer JOB)
References waxpy(), and wdiv().
wlog()
subroutine wlog (double precision XR, double precision XI, double precision YR, double precision YI)
References error().
wmul()
subroutine wmul (double precision AR, double precision AI, double precision BR, double precision BI, double precision CR, double precision CI)
wnrm2()
double precision function wnrm2 (N, double precision, dimension(1) XR, double precision, dimension(1) XI, INCX)
References pythag().
wpofa()
subroutine wpofa (double precision, dimension(lda,1) AR, double precision, dimension(lda,1) AI, LDA, N, INFO)
References wdiv().
wqrdc()
subroutine wqrdc (double precision, dimension(ldx,1) XR, double precision, dimension(ldx,1) XI, integer LDX, integer N, integer P, double precision, dimension(1) QRAUXR, double precision, dimension(1) QRAUXI, integer, dimension(1) JPVT, double precision, dimension(1) WORKR, double precision, dimension(1) WORKI, integer JOB)
References waxpy(), wdiv(), wscal(), wsign(), and wswap().
wqrsl()
subroutine wqrsl (double precision, dimension(ldx,1) XR, double precision, dimension(ldx,1) XI, integer LDX, integer N, integer K, double precision, dimension(1) QRAUXR, double precision, dimension(1) QRAUXI, double precision, dimension(1) YR, double precision, dimension(1) YI, double precision, dimension(1) QYR, double precision, dimension(1) QYI, double precision, dimension(1) QTYR, double precision, dimension(1) QTYI, double precision, dimension(1) BR, double precision, dimension(1) BI, double precision, dimension(1) RSDR, double precision, dimension(1) RSDI, double precision, dimension(1) XBR, double precision, dimension(1) XBI, integer JOB, integer INFO)
References waxpy(), wcopy(), and wdiv().
wrscal()
subroutine wrscal (N, double precision S, double precision, dimension(1) XR, double precision, dimension(1) XI, INCX)
wscal()
subroutine wscal (N, double precision SR, double precision SI, double precision, dimension(1) XR, double precision, dimension(1) XI, INCX)
References wmul().
wset()
subroutine wset (integer N, double precision XR, double precision XI, double precision, dimension(1) YR, double precision, dimension(1) YI, integer INCY)
wsign()
subroutine wsign (double precision XR, double precision XI, double precision YR, double precision YI, double precision ZR, double precision ZI)
References wmul().
wsqrt()
subroutine wsqrt (double precision XR, double precision XI, double precision YR, double precision YI)
wsvdc()
subroutine wsvdc (double precision, dimension(ldx,1) XR, double precision, dimension(ldx,1) XI, integer LDX, integer N, integer P, double precision, dimension(1) SR, double precision, dimension(1) SI, double precision, dimension(1) ER, double precision, dimension(1) EI, double precision, dimension(ldu,1) UR, double precision, dimension(ldu,1) UI, integer LDU, double precision, dimension(ldv,1) VR, double precision, dimension(ldv,1) VI, integer LDV, double precision, dimension(1) WORKR, double precision, dimension(1) WORKI, integer JOB, integer INFO)
References rrot(), rrotg(), waxpy(), wdiv(), wmul(), wrscal(), wscal(), wsign(), and wswap().
wswap()
subroutine wswap (N, double precision, dimension(1) XR, double precision, dimension(1) XI, INCX, double precision, dimension(1) YR, double precision, dimension(1) YI, INCY)
xchar()
subroutine xchar (integer, dimension(*) BUF, integer K)