M_strings: m_matrix Module Reference
m_matrix Module Reference
Functions/Subroutines
subroutine, public mat88 (init, string0)
subroutine mat_err (n)
subroutine mat_files (lunit, iname)
subroutine mat_getsym ()
subroutine mat_str2buf (string, buf, lrecl)
subroutine mat_buf2str (string, buf, lrecl)
subroutine mat_hilber (a, lda, n)
subroutine mat_matfn6 ()
subroutine mat_funs (id)
subroutine mat_putid (x, y)
subroutine mat_getval (s)
subroutine mat_getch ()
doubleprecision function mat_wdotur (n, xr, xi, incx, yr, yi, incy)
subroutine mat_appnum (rval, string, ilen, ierr)
subroutine mat_wcopy (n, xr, xi, incx, yr, yi, incy)
subroutine mat_wdiv (ar, ai, br, bi, cr, ci)
subroutine mat_wset (n, xr, xi, yr, yi, incy)
subroutine mat_base (x, b, eps, s, n)
subroutine mat_wswap (n, xr, xi, incx, yr, yi, incy)
doubleprecision function mat_pythag (a, b)
subroutine mat_print (ID, K)
subroutine mat_wsqrt (xr, xi, yr, yi)
subroutine mat_wlog (xr, xi, yr, yi)
subroutine ml_formz (lunit, x, y)
subroutine mat_rref (ar, ai, lda, m, n, eps)
integer function mat_iwamax (n, xr, xi, incx)
doubleprecision function mat_flop (x)
logical function mat_eqid (x, y)
doubleprecision function mat_round (x)
subroutine mat_make_help (io)
subroutine mat_make_manual (io)
Variables
integer, parameter bigmem =200005
character(len=1024), save stringq
integer, save istringq
integer, save initq
integer, parameter ialf =78
doubleprecision, dimension(bigmem) stkr
doubleprecision, dimension(bigmem) stki
integer, dimension(4, 48) idstk
integer, dimension(48) lstk
integer, dimension(48) mstk
integer, dimension(48) nstk
integer vsize
integer lsize
integer bot
integer top
integer, dimension(ialf) alfa
integer, dimension(ialf) alfb
integer alflq
integer case
integer, dimension(4, 32) ids
integer, dimension(32) pstk
integer, dimension(32) rstk
integer psize
integer pt
integer ptz
integer ddt
integer err
integer fmt
integer, dimension(4) lct
integer, dimension(1024) lin
integer, dimension(6) lpt
integer hio
integer rio
integer rte
integer wte
integer fe
integer sym
integer, dimension(4) syn
integer, dimension(1024) buf
integer chra
integer, dimension(2) flp
integer fin
integer fun
integer lhs
integer rhs
integer, dimension(2) ran
character(len=ialf), parameter ch_a ='0123456789abcdefghijklmnopqrstuvwxyz ();:+-*/\=.,''<>ABCDEFGHIJKLMNOPQRSTUVWXYZ'
character(len=ialf), parameter ch_b ='0123456789abcdefghijklmnopqrstuvwxyz {};|+-*/$=@,"[]ABCDEFGHIJKLMNOPQRSTUVWXYZ'
integer, parameter eol =99
Function/Subroutine Documentation
mat88()
subroutine, public m_matrix::mat88 (integer init, character(len=*), intent(in) string0)
NAME
MAT88(3f) - [M_matrix] initialize and/or pass commands to matrix laboratory interpreter
SYNOPSIS
subroutine MAT88(init,cmd)
integer,intent(in) :: init character(len=*),intent(in) :: cmd)
DESCRIPTION
MAT88(3f) is modeled on MATLAB(3f) (MATrix LABoratory), a FORTRAN package developed by Argonne National Laboratories for in-house use. It provides comprehensive vector and tensor operations in a package which may be programmed, either through a macro language or through execution of script files.
Matlab is reentrant and recursive. Functions supported include (but are not by any means limited to) sin, cos, tan, arcfunctions, upper triangular, lower triangular, determinants, matrix multiplication, identity, Hilbert matrices, eigenvalues and eigenvectors, matrix roots and products, inversion and so on and so forth.
The HELP command describes using the interpreter.
OPTIONS
INIT flag indicating purpose of call
     0 For ordinary first entry with reads from stdin
    -1 negative for silent initialization (ignores CMD)
     1 positive for subsequent entries, enter command mode
       reading commands from stdin.
     2 subsequent entry , return after doing CMD
CMD MAT88 command to perform
EXAMPLE
Sample program
program demo_MAT88
use M_matrix, only : mat88
call MAT88(0,' ')
end program demo_MAT88
!-------------------------------------------------------------
SUBROUTINE mat88_user(A,M,N,S,T)  ! sample mat88_user routine
! Allows personal  Fortran  subroutines  to  be  linked  into
! MAT88. The subroutine should have the heading
!
!               SUBROUTINE mat88_user(A,M,N,S,T)
!               DOUBLEPRECISION A(M,N),S,T
!
! The MAT88 statement  Y = USER(X,s,t)  results in a call to
! the  subroutine with a copy of the matrix  X  stored in the
! argument A , its column and row dimensions in  M  and  N,
! and  the scalar parameters  S  and  T  stored in  S  and  T
! . If  S and T  are omitted, they are set to  0.0 . After
! the  return,   A  is stored in  Y.  The dimensions  M  and
! N  may be reset within the subroutine.  The statement  Y =
! USER(K)  results in a call with M = 1, N = 1  and  A(1,1) =
! FLOAT(K) .  After the subroutine has been written, it  must
! be compiled and linked to the MAT88 object code within the
! local operating system.
!
integer M,N
DOUBLEPRECISION A(M,N),S,T
!
if(s.eq.0.and.t.eq.0)then
   ! print statistics for matrix, for example
   write(*,*)'m=',m
   write(*,*)'n=',n
   write(*,*)'s=',s
   write(*,*)'t=',t
   DO i10 = 1, M
      write(*,*)(a(i10,i20),i20=1,n)
   enddo
else  ! a(i,j)=a(i,j)*s+t  in a linear fashion
   DO i30 = 1, M
      DO i40 = 1, N
         a(i30,i40)=a(i30,i40)*S+T
      enddo
   enddo
endif
END SUBROUTINE mat88_user
Example 2:
program bigmat use M_matrix, only : mat88 ! pass strings to MAT88 but do not enter interactive mode call mat88(-1,' ') ! initialize call mat88(2,'a=<1 2 3 4; 5 6 7 8>') call mat88(2,'save("file1")') call mat88(2,'help INTRO') end
References alfa, alfb, alflq, bigmem, bot, buf, ch_a, ch_b, ddt, err, flp, fmt, fun, hio, ialf, idstk, initq, istringq, lct, lsize, lstk, mat_files(), mat_matfn6(), mat_parse(), mat_putid(), mat_str2buf(), mat_wset(), ml_matfn1(), ml_matfn2(), ml_matfn3(), ml_matfn4(), ml_matfn5(), mstk, nstk, psize, pt, ptz, ran, rio, rte, stki, stkr, stringq, vsize, and wte.
mat_appnum()
subroutine m_matrix::mat_appnum (real, intent(in) rval, character(len=*) string, integer, intent(out) ilen, integer, intent(out) ierr)
mat_base()
subroutine m_matrix::mat_base (doubleprecision x, doubleprecision b, doubleprecision eps, doubleprecision, dimension(*) s, integer n)
mat_buf2str()
subroutine m_matrix::mat_buf2str (character(len=*) string, integer, dimension(lrecl), intent(in) buf, integer, intent(in) lrecl)
mat_eqid()
logical function m_matrix::mat_eqid (integer, dimension(4), intent(in) x, integer, dimension(4), intent(in) y)
References y().
mat_err()
subroutine m_matrix::mat_err (integer, intent(in) n)
References alfa, bot, buf, err, ids, lpt, lstk, mat_buf2str(), pt, rstk, and vsize.
mat_files()
subroutine m_matrix::mat_files (integer lunit, integer, dimension(256) iname)
References ddt, fe, hio, mat_buf2str(), mat_make_help(), rio, and rte.
mat_flop()
doubleprecision function m_matrix::mat_flop (doubleprecision, intent(in) x)
NAME
mat_flop(3fp) - [M_matrix] count and possibly chop each floating point operation
SYNOPSIS
DESCRIPTION
Count and possibly chop each floating point operation.
SYSTEM DEPENDENT FUNCTION
OPTIONS
NOTES
FLP(1) IS FLOP COUNTER FLP(2) IS NUMBER OF PLACES TO BE CHOPPED
References flp.
mat_funs()
subroutine m_matrix::mat_funs (integer, dimension(4), intent(in) id)
References fin, fun, mat_eqid(), ml_prntid(), and rhs.
mat_getch()
subroutine m_matrix::mat_getch
References chra, eol, lin, and lpt.
mat_getsym()
subroutine m_matrix::mat_getsym
References alfa, alflq, chra, ddt, eol, lpt, mat_flop(), mat_getch(), mat_getval(), ml_prntid(), stki, sym, syn, and vsize.
mat_getval()
subroutine m_matrix::mat_getval (doubleprecision, intent(out) s)
References chra, and mat_getch().
mat_hilber()
subroutine m_matrix::mat_hilber (doubleprecision, dimension(lda,n) a, integer lda, integer n)
mat_iwamax()
integer function m_matrix::mat_iwamax (integer n, doubleprecision, dimension(*) xr, doubleprecision, dimension(*) xi, integer incx)
References p().
mat_make_help()
subroutine m_matrix::mat_make_help (integer, intent(in) io)
mat_make_manual()
subroutine m_matrix::mat_make_manual (integer, intent(in) io)
mat_matfn6()
subroutine m_matrix::mat_matfn6
References bot, ddt, err, fin, flp, lhs, lstk, mat_eqid(), mat_err(), mat_flop(), mat_wcopy(), mat_wdiv(), mat_wset(), ml_magic(), ml_rset(), ml_wmul(), mstk, nstk, ran, rhs, stki, stkr, sym, top, and vsize.
mat_print()
subroutine m_matrix::mat_print (integer, dimension(4) ID, integer K)
References alfa, buf, fmt, lct, lstk, mat_files(), mat_round(), ml_formz(), ml_prntid(), mstk, nstk, rte, stki, stkr, and wte.
mat_putid()
subroutine m_matrix::mat_putid (integer, dimension(4), intent(out) x, integer, dimension(4), intent(in) y)
mat_pythag()
doubleprecision function m_matrix::mat_pythag (doubleprecision a, doubleprecision b)
References ddt, and p().
mat_round()
doubleprecision function m_matrix::mat_round (doubleprecision x)
References y().
mat_rref()
subroutine m_matrix::mat_rref (doubleprecision, dimension(lda,*) ar, doubleprecision, dimension(lda,*) ai, integer, intent(in) lda, integer m, integer n, doubleprecision eps)
References mat_iwamax(), mat_wdiv(), mat_wset(), mat_wswap(), matx_waxpy(), and ml_wscal().
mat_str2buf()
subroutine m_matrix::mat_str2buf (character(len=*), intent(in) string, integer, dimension(lrecl), intent(out) buf, integer, intent(in) lrecl)
mat_wcopy()
subroutine m_matrix::mat_wcopy (integer n, doubleprecision, dimension(*) xr, doubleprecision, dimension(*) xi, integer incx, doubleprecision, dimension(*) yr, doubleprecision, dimension(*) yi, integer incy)
mat_wdiv()
subroutine m_matrix::mat_wdiv (doubleprecision ar, doubleprecision ai, doubleprecision br, doubleprecision bi, doubleprecision cr, doubleprecision ci)
References mat_err(), and mat_flop().
mat_wdotur()
doubleprecision function m_matrix::mat_wdotur (integer, intent(in) n, doubleprecision, dimension(*) xr, doubleprecision, dimension(*) xi, integer incx, doubleprecision, dimension(*) yr, doubleprecision, dimension(*) yi, integer incy)
References mat_flop().
mat_wlog()
subroutine m_matrix::mat_wlog (doubleprecision xr, doubleprecision xi, doubleprecision yr, doubleprecision yi)
References mat_err(), and mat_pythag().
mat_wset()
subroutine m_matrix::mat_wset (integer n, doubleprecision xr, doubleprecision xi, doubleprecision, dimension(*) yr, doubleprecision, dimension(*) yi, integer incy)
mat_wsqrt()
subroutine m_matrix::mat_wsqrt (doubleprecision xr, doubleprecision xi, doubleprecision yr, doubleprecision yi)
References mat_flop(), and mat_pythag().
mat_wswap()
subroutine m_matrix::mat_wswap (integer n, doubleprecision, dimension(*) xr, doubleprecision, dimension(*) xi, integer incx, doubleprecision, dimension(*) yr, doubleprecision, dimension(*) yi, integer incy)
ml_formz()
subroutine m_matrix::ml_formz (integer lunit, doubleprecision, intent(in) x, doubleprecision, intent(in) y)
Variable Documentation
alfa
integer, dimension(ialf) m_matrix::alfa
alfb
integer, dimension(ialf) m_matrix::alfb
alflq
integer m_matrix::alflq
bigmem
integer, parameter m_matrix::bigmem =200005
bot
integer m_matrix::bot
buf
integer, dimension(1024) m_matrix::buf
case
integer m_matrix::case
ch_a
character(len=ialf), parameter m_matrix::ch_a ='0123456789abcdefghijklmnopqrstuvwxyz ();:+-*/\=.,''<>ABCDEFGHIJKLMNOPQRSTUVWXYZ'
ch_b
character(len=ialf), parameter m_matrix::ch_b ='0123456789abcdefghijklmnopqrstuvwxyz {};|+-*/$=@,"[]ABCDEFGHIJKLMNOPQRSTUVWXYZ'
chra
integer m_matrix::chra
ddt
integer m_matrix::ddt
eol
integer, parameter m_matrix::eol =99
err
integer m_matrix::err
fe
integer m_matrix::fe
fin
integer m_matrix::fin
flp
integer, dimension(2) m_matrix::flp
fmt
integer m_matrix::fmt
fun
integer m_matrix::fun
hio
integer m_matrix::hio
ialf
integer, parameter m_matrix::ialf =78
ids
integer, dimension(4,32) m_matrix::ids
idstk
integer, dimension(4,48) m_matrix::idstk
initq
integer, save m_matrix::initq
istringq
integer, save m_matrix::istringq
lct
integer, dimension(4) m_matrix::lct
lhs
integer m_matrix::lhs
lin
integer, dimension(1024) m_matrix::lin
lpt
integer, dimension(6) m_matrix::lpt
lsize
integer m_matrix::lsize
lstk
integer, dimension(48) m_matrix::lstk
mstk
integer, dimension(48) m_matrix::mstk
nstk
integer, dimension(48) m_matrix::nstk
psize
integer m_matrix::psize
pstk
integer, dimension(32) m_matrix::pstk
pt
integer m_matrix::pt
ptz
integer m_matrix::ptz
ran
integer, dimension(2) m_matrix::ran
rhs
integer m_matrix::rhs
rio
integer m_matrix::rio
rstk
integer, dimension(32) m_matrix::rstk
rte
integer m_matrix::rte
stki
doubleprecision, dimension(bigmem) m_matrix::stki
stkr
doubleprecision, dimension(bigmem) m_matrix::stkr
stringq
character(len=1024), save m_matrix::stringq
sym
integer m_matrix::sym
syn
integer, dimension(4) m_matrix::syn
top
integer m_matrix::top
vsize
integer m_matrix::vsize
wte
integer m_matrix::wte