name: macos with gfortran

on: [push, pull_request]

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]
        include:
        - os: macos-latest
          gcc_v: 12
    env:
      FC: gfortran
      GCC_V: ${{ matrix.gcc_v }}
      TZ: UTC+04:00

    steps:
    - name: Checkout code
      uses: actions/checkout@v1

    - name: Install GFortran macOS
      run: |
          ls /usr/local/bin/gfortran-*
          ln -f -s /usr/local/bin/gfortran-${GCC_V} /usr/local/bin/gfortran
          which gfortran-${GCC_V}
          which gfortran

    - name: Install fpm
      run: |
           wget https://raw.githubusercontent.com/urbanjost/index/main/bootstrap/fpm.F90
           mkdir -p /Users/runner/bin
           gfortran fpm.F90 -o /Users/runner/bin/fpm
           ls -l

    - name: Display environment
      run: |
        echo $PATH
        pwd
        uname -a
        ulimit -a
        echo "end" > foo.f90
        gfortran -cpp -E -dM foo.f90
        gfortran --version
        fpm --version
        ulimit -a

    - name: tests MacOS (debug)
      run: |
          ulimit -c unlimited -d unlimited -f unlimited -m unlimited -s unlimited -t unlimited -v unlimited 
          exec 2>&1
          set -x
          fpm test --profile debug --verbose

    - name: tests MacOS (release)
      run: |
          ulimit -c unlimited -d unlimited -f unlimited -m unlimited -s unlimited -t unlimited -v unlimited 
          exec 2>&1
          set -x
          fpm test --profile release --verbose

    - name: cleanup MacOS
      run: ls -ltras
